[32mINFO    [0m root:test_info.py:19 登录断言成功